:concurrency: <%= ENV.fetch('SIDEKIQ_CONCURRENCY', 5) %>
:queues:
  - [critical, 3]
  - [default, 2]
  - [low, 1]

:schedule:
  cleanup_expired_messages:
    cron: '0 * * * *' # Каждый час
    class: CleanupExpiredMessagesJob
    queue: low 